dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 123.56.20.143:2181
  protocol:
    port: 28810

server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:mysql://123.56.20.143:3306/secqiafan
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root

spring:
  datasource:
    url: jdbc:mysql://123.56.20.143:3306/secqiafan?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: g+zB+hpiNxqRXSuRWf9c7kbckMPkkwZ4m0Q7GNoojwVzSIe1fnf13Ctbhe0bId9ZHIlRhU1ncgoAP0IXku/bAg==
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMDmuZypl4chyMPTKoyizKxeJ7741m03C/V6NA/mCNlwfIG1HXRC9YwNmSWIHWbntpN7HnelOM5kk83d4qMyAZ0CAwEAAQ==

#非对称加密
#私钥加密，公钥解密
